
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA DO END FOR ID NUMBER PLUSstatement : for_loop\n| assignmentfor_loop : FOR ID ASSIGN expr COMMA expr DO statements ENDfor_loop : FOR ID ASSIGN expr COMMA expr COMMA expr DO statements ENDstatements : statements statement\n| statementassignment : ID ASSIGN exprexpr : NUMBER\n| ID\n| expr PLUS expr'
    
_lr_action_items = {'FOR':([0,2,3,9,10,11,15,18,20,21,22,23,24,25,26,],[4,-1,-2,-9,-7,-8,-10,4,4,-6,4,-3,-5,4,-4,]),'ID':([0,2,3,4,7,8,9,10,11,13,14,15,17,18,20,21,22,23,24,25,26,],[5,-1,-2,6,9,9,-9,-7,-8,9,9,-10,9,5,5,-6,5,-3,-5,5,-4,]),'$end':([1,2,3,9,10,11,15,23,26,],[0,-1,-2,-9,-7,-8,-10,-3,-4,]),'END':([2,3,9,10,11,15,20,21,23,24,25,26,],[-1,-2,-9,-7,-8,-10,23,-6,-3,-5,26,-4,]),'ASSIGN':([5,6,],[7,8,]),'NUMBER':([7,8,13,14,17,],[11,11,11,11,11,]),'PLUS':([9,10,11,12,15,16,19,],[-9,13,-8,13,13,13,13,]),'COMMA':([9,11,12,15,16,],[-9,-8,14,-10,17,]),'DO':([9,11,15,16,19,],[-9,-8,-10,18,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,18,20,22,25,],[1,21,24,21,24,]),'for_loop':([0,18,20,22,25,],[2,2,2,2,2,]),'assignment':([0,18,20,22,25,],[3,3,3,3,3,]),'expr':([7,8,13,14,17,],[10,12,15,16,19,]),'statements':([18,22,],[20,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> for_loop','statement',1,'p_statement','for_statement.py',58),
  ('statement -> assignment','statement',1,'p_statement','for_statement.py',59),
  ('for_loop -> FOR ID ASSIGN expr COMMA expr DO statements END','for_loop',9,'p_for_loop_three','for_statement.py',63),
  ('for_loop -> FOR ID ASSIGN expr COMMA expr COMMA expr DO statements END','for_loop',11,'p_for_loop_four','for_statement.py',67),
  ('statements -> statements statement','statements',2,'p_statements','for_statement.py',71),
  ('statements -> statement','statements',1,'p_statements','for_statement.py',72),
  ('assignment -> ID ASSIGN expr','assignment',3,'p_assignment','for_statement.py',76),
  ('expr -> NUMBER','expr',1,'p_expr','for_statement.py',80),
  ('expr -> ID','expr',1,'p_expr','for_statement.py',81),
  ('expr -> expr PLUS expr','expr',3,'p_expr','for_statement.py',82),
]
