
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ELSE END ID IF NUMBER OP PLUS THENstatement : if_statement\n| assignmentif_statement : IF condition THEN statements END\n| IF condition THEN statements ELSE statements ENDcondition : ID OP exprstatements : statements statement\n| statementassignment : ID ASSIGN exprexpr : NUMBER\n| ID\n| expr PLUS expr'
    
_lr_action_items = {'IF':([0,2,3,9,11,12,13,14,15,18,19,20,21,22,23,],[4,-1,-2,4,-10,-8,-9,4,-7,-3,4,-6,-11,4,-4,]),'ID':([0,2,3,4,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,],[5,-1,-2,7,11,5,11,-10,-8,-9,5,-7,11,-3,5,-6,-11,5,-4,]),'$end':([1,2,3,11,12,13,18,21,23,],[0,-1,-2,-10,-8,-9,-3,-11,-4,]),'END':([2,3,11,12,13,14,15,18,20,21,22,23,],[-1,-2,-10,-8,-9,18,-7,-3,-6,-11,23,-4,]),'ELSE':([2,3,11,12,13,14,15,18,20,21,23,],[-1,-2,-10,-8,-9,19,-7,-3,-6,-11,-4,]),'ASSIGN':([5,],[8,]),'THEN':([6,11,13,16,21,],[9,-10,-9,-5,-11,]),'OP':([7,],[10,]),'NUMBER':([8,10,17,],[13,13,13,]),'PLUS':([11,12,13,16,21,],[-10,17,-9,17,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,9,14,19,22,],[1,15,20,15,20,]),'if_statement':([0,9,14,19,22,],[2,2,2,2,2,]),'assignment':([0,9,14,19,22,],[3,3,3,3,3,]),'condition':([4,],[6,]),'expr':([8,10,17,],[12,16,21,]),'statements':([9,19,],[14,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> if_statement','statement',1,'p_statement','if-else-statement.py',61),
  ('statement -> assignment','statement',1,'p_statement','if-else-statement.py',62),
  ('if_statement -> IF condition THEN statements END','if_statement',5,'p_if_statement','if-else-statement.py',66),
  ('if_statement -> IF condition THEN statements ELSE statements END','if_statement',7,'p_if_statement','if-else-statement.py',67),
  ('condition -> ID OP expr','condition',3,'p_condition','if-else-statement.py',71),
  ('statements -> statements statement','statements',2,'p_statements','if-else-statement.py',75),
  ('statements -> statement','statements',1,'p_statements','if-else-statement.py',76),
  ('assignment -> ID ASSIGN expr','assignment',3,'p_assignment','if-else-statement.py',80),
  ('expr -> NUMBER','expr',1,'p_expr','if-else-statement.py',84),
  ('expr -> ID','expr',1,'p_expr','if-else-statement.py',85),
  ('expr -> expr PLUS expr','expr',3,'p_expr','if-else-statement.py',86),
]
